language: node_js
node_js:
- 10
env:
- NODE_ENV=production
script:
- eval "$(ssh-agent -s)"
- ssh-keyscan -H 195.133.1.169 >> ~/.ssh/known_hosts
- chmod 600 $HOME/.ssh/id_rsa-ru_vds-food
- ssh-add $HOME/.ssh/id_rsa-ru_vds-food
- scp -r ./ root@195.133.1.169:/home/food-backend
- ssh root@195.133.1.169 'dropdb android_app'
- ssh root@195.133.1.169 'cd ../home/food-backend; createdb -O igor android_app; psql android_app < android_app.sql;'
- ssh root@195.133.1.169 'source ~/.nvm/nvm.sh; nvm use 10.0.0; cd ../home/food-backend; npm i; killall node; nohup nodemon -I ./server/server.js &'
before_install:
- openssl aes-256-cbc -K $encrypted_26bd407dd73f_key -iv $encrypted_26bd407dd73f_iv
  -in id_rsa-ru_vds-food.enc -out $HOME/.ssh/id_rsa-ru_vds-food -d
